#version 430 core

layout (std430, binding = 0) buffer b0
{
  vec2 x[];
};

layout (std430, binding = 1) buffer b1
{
  vec2 v[];
};

layout (local_size_x = 256) in;

void main()
{
  float dt = 0.02;
  uint i = gl_GlobalInvocationID.x;
  v[i] -= vec2(0.0, 1.0) * dt;
  if (x[i].x > +1 && v[i].x > 0) v[i].x *= -1;
  if (x[i].x < -1 && v[i].x < 0) v[i].x *= -1;
  if (x[i].y > +1 && v[i].y > 0) v[i].y *= -1;
  if (x[i].y < -1 && v[i].y < 0) v[i].y *= -1;
}
