#version 430 core

layout (std430, binding = 0) buffer b_particles
{
  vec2 pos[3];
  vec2 vel[3];
};

layout (local_size_x = 3) in;

void main()
{
  float dt = 0.02;
  uint i = gl_GlobalInvocationID.x;
  vel[i] -= vec2(0.0, 1.0) * dt;
  if (pos[i].x > +1 && vel[i].x > 0) vel[i].x *= -1;
  if (pos[i].x < -1 && vel[i].x < 0) vel[i].x *= -1;
  if (pos[i].y > +1 && vel[i].y > 0) vel[i].y *= -1;
  if (pos[i].y < -1 && vel[i].y < 0) vel[i].y *= -1;
}
